import 'package:flutter/material.dart';

// ============================================================================
// UNIFIED COLOR SYSTEM - Used throughout the app for consistency
// ============================================================================

// PRIMARY TEAL COLORS (for text and accents)
/// Primary light teal - used for main accent text and UI elements
const Color kPrimaryTeal = Color(0xFF1ABC9C);

/// Secondary Light cyan/teal - used for secondary accent text and highlights
const Color kSecondaryTeal = Color(0xFF64FFDA);

/// Dark teal - used for heading text and dark backgrounds in light mode
const Color kDarkTeal = Color(0xFF0D7377);

/// Tertiary teal - used as alternative teal accent
const Color kTertiaryTeal = Color(0xFF14919B);

// ORANGE COLOR (for text and accents)
/// Orange accent color - used for highlighting and important elements
const Color kOrangeAccent = Color(0xFFFF9500);

// BACKGROUND COLORS
/// Dark background - used for dark mode background
const Color kDarkBackground = Color(0xFF1E1E2C);

/// Dark background variant - used for dark mode variations
const Color kDarkBackgroundVariant = Color(0xFF12121D);

/// Dark background alternative - used in specific components
const Color kDarkBackgroundAlt = Color(0xFF232537);

/// Light background - used for light mode background
const Color kLightBackground = Color.fromARGB(255, 255, 255, 255);

/// Light background variant - used for light mode surfaces
const Color kLightBackgroundVariant = Color.fromARGB(255, 255, 255, 255);

// LEGACY CONSTANT (for backward compatibility)
@deprecated
const Color kLightsColor = kPrimaryTeal;

class ThumonEntry {
  final String file;
  final String surah;
  const ThumonEntry({required this.file, required this.surah});
}

/// A constant list of all thomun text filenames and their corresponding Surah names.
List<ThumonEntry> kThomunsTxt = [
  const ThumonEntry(file: '1-1.txt', surah: 'سورة الفاتحة / البقرة'),
  const ThumonEntry(file: '1-2.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '1-3.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '1-4.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '1-5.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '1-6.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '1-7.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '1-8.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '2-1.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '2-2.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '2-3.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '2-4.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '2-5.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '2-6.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '2-7.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '2-8.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '3-1.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '3-2.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '3-3.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '3-4.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '3-5.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '3-6.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '3-7.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '3-8.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '4-1.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '4-2.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '4-3.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '4-4.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '4-5.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '4-6.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '4-7.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '4-8.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '5-1.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '5-2.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '5-3.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '5-4.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '5-5.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '5-6.txt', surah: 'سورة البقرة'),
  const ThumonEntry(file: '5-7.txt', surah: 'سورة البقرة و آل عمران'),
  const ThumonEntry(file: '5-8.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '6-1.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '6-2.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '6-3.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '6-4.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '6-5.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '6-6.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '6-7.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '6-8.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '7-1.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '7-2.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '7-3.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '7-4.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '7-5.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '7-6.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '7-7.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '7-8.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '8-1.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '8-2.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '8-3.txt', surah: 'سورة آل عمران'),
  const ThumonEntry(file: '8-4.txt', surah: 'سورة آل عمران و النساء'),
  const ThumonEntry(file: '8-5.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '8-6.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '8-7.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '8-8.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '9-1.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '9-2.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '9-3.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '9-4.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '9-5.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '9-6.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '9-7.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '9-8.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '10-1.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '10-2.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '10-3.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '10-4.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '10-5.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '10-6.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '10-7.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '10-8.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '11-1.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '11-2.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '11-3.txt', surah: 'سورة النساء'),
  const ThumonEntry(file: '11-4.txt', surah: 'سورة النساء و المائدة'),
  const ThumonEntry(file: '11-5.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '11-6.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '11-7.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '11-8.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '12-1.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '12-2.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '12-3.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '12-4.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '12-5.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '12-6.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '12-7.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '12-8.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '13-1.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '13-2.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '13-3.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '13-4.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '13-5.txt', surah: 'سورة المائدة'),
  const ThumonEntry(file: '13-6.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '13-7.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '13-8.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '14-1.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '14-2.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '14-3.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '14-4.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '14-5.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '14-6.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '14-7.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '14-8.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '15-1.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '15-2.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '15-3.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '15-4.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '15-5.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '15-6.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '15-7.txt', surah: 'سورة الأنعام'),
  const ThumonEntry(file: '15-8.txt', surah: 'سورة الأنعام و الأعراف'),
  const ThumonEntry(file: '16-1.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '16-2.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '16-3.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '16-4.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '16-5.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '16-6.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '16-7.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '16-8.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '17-1.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '17-2.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '17-3.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '17-4.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '17-5.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '17-6.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '17-7.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '17-8.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '18-1.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '18-2.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '18-3.txt', surah: 'سورة الأعراف'),
  const ThumonEntry(file: '18-4.txt', surah: 'سورة الأعراف و الأنفال'),
  const ThumonEntry(file: '18-5.txt', surah: 'سورة الأنفال'),
  const ThumonEntry(file: '18-6.txt', surah: 'سورة الأنفال'),
  const ThumonEntry(file: '18-7.txt', surah: 'سورة الأنفال'),
  const ThumonEntry(file: '18-8.txt', surah: 'سورة الأنفال'),
  const ThumonEntry(file: '19-1.txt', surah: 'سورة الأنفال'),
  const ThumonEntry(file: '19-2.txt', surah: 'سورة الأنفال'),
  const ThumonEntry(file: '19-3.txt', surah: 'سورة الأنفال'),
  const ThumonEntry(file: '19-4.txt', surah: 'سورة الأنفال و التوبة'),
  const ThumonEntry(file: '19-5.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '19-6.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '19-7.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '19-8.txt', surah: 'سورة التوبة '),
  const ThumonEntry(file: '20-1.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '20-2.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '20-3.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '20-4.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '20-5.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '20-6.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '20-7.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '20-8.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '21-1.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '21-2.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '21-3.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '21-4.txt', surah: 'سورة التوبة'),
  const ThumonEntry(file: '21-5.txt', surah: 'سورة التوبة و يونس'),
  const ThumonEntry(file: '21-6.txt', surah: 'سورة يونس'),
  const ThumonEntry(file: '21-7.txt', surah: 'سورة يونس'),
  const ThumonEntry(file: '21-8.txt', surah: 'سورة يونس'),
  const ThumonEntry(file: '22-1.txt', surah: 'سورة يونس'),
  const ThumonEntry(file: '22-2.txt', surah: 'سورة يونس'),
  const ThumonEntry(file: '22-3.txt', surah: 'سورة يونس'),
  const ThumonEntry(file: '22-4.txt', surah: 'سورة يونس'),
  const ThumonEntry(file: '22-5.txt', surah: 'سورة يونس'),
  const ThumonEntry(file: '22-6.txt', surah: 'سورة يونس'),
  const ThumonEntry(file: '22-7.txt', surah: 'سورة يونس'),
  const ThumonEntry(file: '22-8.txt', surah: 'سورة يونس و هود'),
  const ThumonEntry(file: '23-1.txt', surah: 'سورة هود'),
  const ThumonEntry(file: '23-2.txt', surah: 'سورة هود'),
  const ThumonEntry(file: '23-3.txt', surah: 'سورة هود'),
  const ThumonEntry(file: '23-4.txt', surah: 'سورة هود'),
  const ThumonEntry(file: '23-5.txt', surah: 'سورة هود'),
  const ThumonEntry(file: '23-6.txt', surah: 'سورة هود'),
  const ThumonEntry(file: '23-7.txt', surah: 'سورة هود'),
  const ThumonEntry(file: '23-8.txt', surah: 'سورة هود'),
  const ThumonEntry(file: '24-1.txt', surah: 'سورة هود'),
  const ThumonEntry(file: '24-2.txt', surah: 'سورة هود'),
  const ThumonEntry(file: '24-3.txt', surah: 'سورة هود'),
  const ThumonEntry(file: '24-4.txt', surah: 'سورة هود و  يوسف'),
  const ThumonEntry(file: '24-5.txt', surah: 'سورة يوسف'),
  const ThumonEntry(file: '24-6.txt', surah: 'سورة يوسف'),
  const ThumonEntry(file: '24-7.txt', surah: 'سورة يوسف'),
  const ThumonEntry(file: '24-8.txt', surah: 'سورة يوسف'),
  const ThumonEntry(file: '25-1.txt', surah: 'سورة يوسف'),
  const ThumonEntry(file: '25-2.txt', surah: 'سورة يوسف'),
  const ThumonEntry(file: '25-3.txt', surah: 'سورة يوسف'),
  const ThumonEntry(file: '25-4.txt', surah: 'سورة يوسف'),
  const ThumonEntry(file: '25-5.txt', surah: 'سورة يوسف'),
  const ThumonEntry(file: '25-6.txt', surah: 'سورة الرعد'),
  const ThumonEntry(file: '25-7.txt', surah: 'سورة الرعد'),
  const ThumonEntry(file: '25-8.txt', surah: 'سورة الرعد'),
  const ThumonEntry(file: '26-1.txt', surah: 'سورة الرعد'),
  const ThumonEntry(file: '26-2.txt', surah: 'سورة الرعد'),
  const ThumonEntry(file: '26-3.txt', surah: 'سورة الرعد'),
  const ThumonEntry(file: '26-4.txt', surah: 'سورة إبراهيم'),
  const ThumonEntry(file: '26-5.txt', surah: 'سورة إبراهيم'),
  const ThumonEntry(file: '26-6.txt', surah: 'سورة إبراهيم'),
  const ThumonEntry(file: '26-7.txt', surah: 'سورة إبراهيم'),
  const ThumonEntry(file: '26-8.txt', surah: 'سورة إبراهيم'),
  const ThumonEntry(file: '27-1.txt', surah: 'سورة الحجر'),
  const ThumonEntry(file: '27-2.txt', surah: 'سورة الحجر'),
  const ThumonEntry(file: '27-3.txt', surah: 'سورة الحجر'),
  const ThumonEntry(file: '27-4.txt', surah: 'سورة الحجر'),
  const ThumonEntry(file: '27-5.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '27-6.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '27-7.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '27-8.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '28-1.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '28-2.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '28-3.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '28-4.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '28-5.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '28-6.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '28-7.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '28-8.txt', surah: 'سورة النحل'),
  const ThumonEntry(file: '29-1.txt', surah: 'سورة الإسراء'),
  const ThumonEntry(file: '29-2.txt', surah: 'سورة الإسراء'),
  const ThumonEntry(file: '29-3.txt', surah: 'سورة الإسراء'),
  const ThumonEntry(file: '29-4.txt', surah: 'سورة الإسراء'),
  const ThumonEntry(file: '29-5.txt', surah: 'سورة الإسراء'),
  const ThumonEntry(file: '29-6.txt', surah: 'سورة الإسراء'),
  const ThumonEntry(file: '29-7.txt', surah: 'سورة الإسراء'),
  const ThumonEntry(file: '29-8.txt', surah: 'سورة الإسراء'),
  const ThumonEntry(file: '30-1.txt', surah: 'سورة الإسراء'),
  const ThumonEntry(file: '30-2.txt', surah: 'سورة الكهف'),
  const ThumonEntry(file: '30-3.txt', surah: 'سورة الكهف'),
  const ThumonEntry(file: '30-4.txt', surah: 'سورة الكهف'),
  const ThumonEntry(file: '30-5.txt', surah: 'سورة الكهف'),
  const ThumonEntry(file: '30-6.txt', surah: 'سورة الكهف'),
  const ThumonEntry(file: '30-7.txt', surah: 'سورة الكهف'),
  const ThumonEntry(file: '30-8.txt', surah: 'سورة الكهف'),
  const ThumonEntry(file: '31-1.txt', surah: 'سورة الكهف'),
  const ThumonEntry(file: '31-2.txt', surah: 'سورة الكهف'),
  const ThumonEntry(file: '31-3.txt', surah: 'سورة الكهف و مريم'),
  const ThumonEntry(file: '31-4.txt', surah: 'سورة مريم'),
  const ThumonEntry(file: '31-5.txt', surah: 'سورة مريم'),
  const ThumonEntry(file: '31-6.txt', surah: 'سورة مريم'),
  const ThumonEntry(file: '31-7.txt', surah: 'سورة مريم'),
  const ThumonEntry(file: '31-8.txt', surah: 'سورة مريم'),
  const ThumonEntry(file: '32-1.txt', surah: 'سورة طه'),
  const ThumonEntry(file: '32-2.txt', surah: 'سورة طه'),
  const ThumonEntry(file: '32-3.txt', surah: 'سورة طه'),
  const ThumonEntry(file: '32-4.txt', surah: 'سورة طه'),
  const ThumonEntry(file: '32-5.txt', surah: 'سورة طه'),
  const ThumonEntry(file: '32-6.txt', surah: 'سورة طه'),
  const ThumonEntry(file: '32-7.txt', surah: 'سورة طه'),
  const ThumonEntry(file: '32-8.txt', surah: 'سورة طه'),
  const ThumonEntry(file: '33-1.txt', surah: 'سورة الأنبياء'),
  const ThumonEntry(file: '33-2.txt', surah: 'سورة الأنبياء'),
  const ThumonEntry(file: '33-3.txt', surah: 'سورة الأنبياء'),
  const ThumonEntry(file: '33-4.txt', surah: 'سورة الأنبياء'),
  const ThumonEntry(file: '33-5.txt', surah: 'سورة الأنبياء'),
  const ThumonEntry(file: '33-6.txt', surah: 'سورة الأنبياء'),
  const ThumonEntry(file: '33-7.txt', surah: 'سورة الأنبياء'),
  const ThumonEntry(file: '33-8.txt', surah: 'سورة الأنبياء'),
  const ThumonEntry(file: '34-1.txt', surah: 'سورة الحج'),
  const ThumonEntry(file: '34-2.txt', surah: 'سورة الحج'),
  const ThumonEntry(file: '34-3.txt', surah: 'سورة الحج'),
  const ThumonEntry(file: '34-4.txt', surah: 'سورة الحج'),
  const ThumonEntry(file: '34-5.txt', surah: 'سورة الحج'),
  const ThumonEntry(file: '34-6.txt', surah: 'سورة الحج'),
  const ThumonEntry(file: '34-7.txt', surah: 'سورة الحج'),
  const ThumonEntry(file: '34-8.txt', surah: 'سورة الحج'),
  const ThumonEntry(file: '35-1.txt', surah: 'سورة المؤمنون'),
  const ThumonEntry(file: '35-2.txt', surah: 'سورة المؤمنون'),
  const ThumonEntry(file: '35-3.txt', surah: 'سورة المؤمنون'),
  const ThumonEntry(file: '35-4.txt', surah: 'سورة المؤمنون'),
  const ThumonEntry(file: '35-5.txt', surah: 'سورة المؤمنون'),
  const ThumonEntry(file: '35-6.txt', surah: 'سورة المؤمنون'),
  const ThumonEntry(file: '35-7.txt', surah: 'سورة المؤمنون و النور'),
  const ThumonEntry(file: '35-8.txt', surah: 'سورة النور'),
  const ThumonEntry(file: '36-1.txt', surah: 'سورة النور'),
  const ThumonEntry(file: '36-2.txt', surah: 'سورة النور'),
  const ThumonEntry(file: '36-3.txt', surah: 'سورة النور'),
  const ThumonEntry(file: '36-4.txt', surah: 'سورة النور'),
  const ThumonEntry(file: '36-5.txt', surah: 'سورة النور'),
  const ThumonEntry(file: '36-6.txt', surah: 'سورة النور'),
  const ThumonEntry(file: '36-7.txt', surah: 'سورة النور و الفرقان'),
  const ThumonEntry(file: '36-8.txt', surah: 'سورة الفرقان'),
  const ThumonEntry(file: '37-1.txt', surah: 'سورة الفرقان'),
  const ThumonEntry(file: '37-2.txt', surah: 'سورة الفرقان'),
  const ThumonEntry(file: '37-3.txt', surah: 'سورة الفرقان'),
  const ThumonEntry(file: '37-4.txt', surah: 'سورة الفرقان'),
  const ThumonEntry(file: '37-5.txt', surah: 'سورة الشعراء'),
  const ThumonEntry(file: '37-6.txt', surah: 'سورة الشعراء'),
  const ThumonEntry(file: '37-7.txt', surah: 'سورة الشعراء'),
  const ThumonEntry(file: '37-8.txt', surah: 'سورة الشعراء'),
  const ThumonEntry(file: '38-1.txt', surah: 'سورة الشعراء'),
  const ThumonEntry(file: '38-2.txt', surah: 'سورة الشعراء'),
  const ThumonEntry(file: '38-3.txt', surah: 'سورة الشعراء'),
  const ThumonEntry(file: '38-4.txt', surah: 'سورة الشعراء و النمل'),
  const ThumonEntry(file: '38-5.txt', surah: 'سورة النمل'),
  const ThumonEntry(file: '38-6.txt', surah: 'سورة النمل'),
  const ThumonEntry(file: '38-7.txt', surah: 'سورة النمل'),
  const ThumonEntry(file: '38-8.txt', surah: 'سورة النمل'),
  const ThumonEntry(file: '39-1.txt', surah: 'سورة النمل'),
  const ThumonEntry(file: '39-2.txt', surah: 'سورة النمل'),
  const ThumonEntry(file: '39-3.txt', surah: 'سورة النمل'),
  const ThumonEntry(file: '39-4.txt', surah: 'سورة القصص'),
  const ThumonEntry(file: '39-5.txt', surah: 'سورة القصص'),
  const ThumonEntry(file: '39-6.txt', surah: 'سورة القصص'),
  const ThumonEntry(file: '39-7.txt', surah: 'سورة القصص'),
  const ThumonEntry(file: '39-8.txt', surah: 'سورة القصص'),
  const ThumonEntry(file: '40-1.txt', surah: 'سورة القصص'),
  const ThumonEntry(file: '40-2.txt', surah: 'سورة القصص'),
  const ThumonEntry(file: '40-3.txt', surah: 'سورة القصص'),
  const ThumonEntry(file: '40-4.txt', surah: 'سورة القصص'),
  const ThumonEntry(file: '40-5.txt', surah: 'سورة العنكبوت'),
  const ThumonEntry(file: '40-6.txt', surah: 'سورة العنكبوت'),
  const ThumonEntry(file: '40-7.txt', surah: 'سورة العنكبوت'),
  const ThumonEntry(file: '40-8.txt', surah: 'سورة العنكبوت'),
  const ThumonEntry(file: '41-1.txt', surah: 'سورة العنكبوت'),
  const ThumonEntry(file: '41-2.txt', surah: 'سورة العنكبوت و الروم'),
  const ThumonEntry(file: '41-3.txt', surah: 'سورة الروم'),
  const ThumonEntry(file: '41-4.txt', surah: 'سورة الروم'),
  const ThumonEntry(file: '41-5.txt', surah: 'سورة الروم'),
  const ThumonEntry(file: '41-6.txt', surah: 'سورة الروم'),
  const ThumonEntry(file: '41-7.txt', surah: 'سورة الروم و لقمان'),
  const ThumonEntry(file: '41-8.txt', surah: 'سورة لقمان'),
  const ThumonEntry(file: '42-1.txt', surah: 'سورة لقمان'),
  const ThumonEntry(file: '42-2.txt', surah: 'سورة لقمان و السجدة'),
  const ThumonEntry(file: '42-3.txt', surah: 'سورة السجدة'),
  const ThumonEntry(file: '42-4.txt', surah: 'سورة السجدة'),
  const ThumonEntry(file: '42-5.txt', surah: 'سورة الأحزاب'),
  const ThumonEntry(file: '42-6.txt', surah: 'سورة الأحزاب'),
  const ThumonEntry(file: '42-7.txt', surah: 'سورة الأحزاب'),
  const ThumonEntry(file: '42-8.txt', surah: 'سورة الأحزاب'),
  const ThumonEntry(file: '43-1.txt', surah: 'سورة الأحزاب'),
  const ThumonEntry(file: '43-2.txt', surah: 'سورة الأحزاب'),
  const ThumonEntry(file: '43-3.txt', surah: 'سورة الأحزاب'),
  const ThumonEntry(file: '43-4.txt', surah: 'سورة الأحزاب'),
  const ThumonEntry(file: '43-5.txt', surah: 'سورة الأحزاب'),
  const ThumonEntry(file: '43-6.txt', surah: 'سورة سبأ'),
  const ThumonEntry(file: '43-7.txt', surah: 'سورة سبأ'),
  const ThumonEntry(file: '43-8.txt', surah: 'سورة سبأ'),
  const ThumonEntry(file: '44-1.txt', surah: 'سورة سبأ'),
  const ThumonEntry(file: '44-2.txt', surah: 'سورة سبأ'),
  const ThumonEntry(file: '44-3.txt', surah: 'سورة سبأ و فاطر'),
  const ThumonEntry(file: '44-4.txt', surah: 'سورة فاطر'),
  const ThumonEntry(file: '44-5.txt', surah: 'سورة فاطر'),
  const ThumonEntry(file: '44-6.txt', surah: 'سورة فاطر'),
  const ThumonEntry(file: '44-7.txt', surah: 'سورة فاطر و يس'),
  const ThumonEntry(file: '44-8.txt', surah: 'سورة يس'),
  const ThumonEntry(file: '45-1.txt', surah: 'سورة يس'),
  const ThumonEntry(file: '45-2.txt', surah: 'سورة يس'),
  const ThumonEntry(file: '45-3.txt', surah: 'سورة يس'),
  const ThumonEntry(file: '45-4.txt', surah: 'سورة يس و الصافات'),
  const ThumonEntry(file: '45-5.txt', surah: 'سورة الصافات'),
  const ThumonEntry(file: '45-6.txt', surah: 'سورة الصافات'),
  const ThumonEntry(file: '45-7.txt', surah: 'سورة الصافات'),
  const ThumonEntry(file: '45-8.txt', surah: 'سورة الصافات'),
  const ThumonEntry(file: '46-1.txt', surah: 'سورة الصافات'),
  const ThumonEntry(file: '46-2.txt', surah: 'سورة ص'),
  const ThumonEntry(file: '46-3.txt', surah: 'سورة ص'),
  const ThumonEntry(file: '46-4.txt', surah: 'سورة ص'),
  const ThumonEntry(file: '46-5.txt', surah: 'سورة ص'),
  const ThumonEntry(file: '46-6.txt', surah: 'سورة ص و الزمر'),
  const ThumonEntry(file: '46-7.txt', surah: 'سورة الزمر'),
  const ThumonEntry(file: '46-8.txt', surah: 'سورة الزمر'),
  const ThumonEntry(file: '47-1.txt', surah: 'سورة الزمر'),
  const ThumonEntry(file: '47-2.txt', surah: 'سورة الزمر'),
  const ThumonEntry(file: '47-3.txt', surah: 'سورة الزمر'),
  const ThumonEntry(file: '47-4.txt', surah: 'سورة الزمر'),
  const ThumonEntry(file: '47-5.txt', surah: 'سورة غافر'),
  const ThumonEntry(file: '47-6.txt', surah: 'سورة غافر'),
  const ThumonEntry(file: '47-7.txt', surah: 'سورة غافر'),
  const ThumonEntry(file: '47-8.txt', surah: 'سورة غافر'),
  const ThumonEntry(file: '48-1.txt', surah: 'سورة غافر'),
  const ThumonEntry(file: '48-2.txt', surah: 'سورة غافر'),
  const ThumonEntry(file: '48-3.txt', surah: 'سورة غافر'),
  const ThumonEntry(file: '48-4.txt', surah: 'سورة غافر و فصلت'),
  const ThumonEntry(file: '48-5.txt', surah: 'سورة فصلت'),
  const ThumonEntry(file: '48-6.txt', surah: 'سورة فصلت'),
  const ThumonEntry(file: '48-7.txt', surah: 'سورة فصلت'),
  const ThumonEntry(file: '48-8.txt', surah: 'سورة فصلت'),
  const ThumonEntry(file: '49-1.txt', surah: 'سورة فصلت و الشورى'),
  const ThumonEntry(file: '49-2.txt', surah: 'سورة الشورى'),
  const ThumonEntry(file: '49-3.txt', surah: 'سورة الشورى'),
  const ThumonEntry(file: '49-4.txt', surah: 'سورة الشورى'),
  const ThumonEntry(file: '49-5.txt', surah: 'سورة الشورى'),
  const ThumonEntry(file: '49-6.txt', surah: 'سورة الشورى'),
  const ThumonEntry(file: '49-7.txt', surah: 'سورة الشورى و الزخرف'),
  const ThumonEntry(file: '49-8.txt', surah: 'سورة الزخرف'),
  const ThumonEntry(file: '50-1.txt', surah: 'سورة الزخرف'),
  const ThumonEntry(file: '50-2.txt', surah: 'سورة الزخرف'),
  const ThumonEntry(file: '50-3.txt', surah: 'سورة الزخرف'),
  const ThumonEntry(file: '50-4.txt', surah: 'سورة الزخرف و الدخان'),
  const ThumonEntry(file: '50-5.txt', surah: 'سورة الدخان'),
  const ThumonEntry(file: '50-6.txt', surah: 'سورة الجاثية'),
  const ThumonEntry(file: '50-7.txt', surah: 'سورة الجاثية'),
  const ThumonEntry(file: '50-8.txt', surah: 'سورة الجاثية'),
  const ThumonEntry(file: '51-1.txt', surah: 'سورة الأحقاف'),
  const ThumonEntry(file: '51-2.txt', surah: 'سورة الأحقاف'),
  const ThumonEntry(file: '51-3.txt', surah: 'سورة الأحقاف'),
  const ThumonEntry(file: '51-4.txt', surah: 'سورة الأحقاف و محمد'),
  const ThumonEntry(file: '51-5.txt', surah: 'سورة محمد'),
  const ThumonEntry(file: '51-6.txt', surah: 'سورة محمد'),
  const ThumonEntry(file: '51-7.txt', surah: 'سورة محمد و الفتح'),
  const ThumonEntry(file: '51-8.txt', surah: 'سورة الفتح'),
  const ThumonEntry(file: '52-1.txt', surah: 'سورة الفتح'),
  const ThumonEntry(file: '52-2.txt', surah: 'سورة الفتح'),
  const ThumonEntry(file: '52-3.txt', surah: 'سورة الحجرات'),
  const ThumonEntry(file: '52-4.txt', surah: 'سورة الحجرات'),
  const ThumonEntry(file: '52-5.txt', surah: 'سورة الحجرات و ق'),
  const ThumonEntry(file: '52-6.txt', surah: 'سورة ق'),
  const ThumonEntry(file: '52-7.txt', surah: 'سورة ق'),
  const ThumonEntry(file: '52-8.txt', surah: 'سورة الذاريات'),
  const ThumonEntry(file: '53-1.txt', surah: 'سورة الذاريات'),
  const ThumonEntry(file: '53-2.txt', surah: 'سورة الذاريات و الطور'),
  const ThumonEntry(file: '53-3.txt', surah: 'سورة الطور'),
  const ThumonEntry(file: '53-4.txt', surah: 'سورة الطور و النجم'),
  const ThumonEntry(file: '53-5.txt', surah: 'سورة النجم'),
  const ThumonEntry(file: '53-6.txt', surah: 'سورة النجم و القمر'),
  const ThumonEntry(file: '53-7.txt', surah: 'سورة القمر'),
  const ThumonEntry(file: '53-8.txt', surah: 'سورة القمر'),
  const ThumonEntry(file: '54-1.txt', surah: 'سورة الرحمان'),
  const ThumonEntry(file: '54-2.txt', surah: 'سورة الرحمان'),
  const ThumonEntry(file: '54-3.txt', surah: 'سورة الواقعة'),
  const ThumonEntry(file: '54-4.txt', surah: 'سورة الواقعة'),
  const ThumonEntry(file: '54-5.txt', surah: 'سورة الواقعة و الحديد'),
  const ThumonEntry(file: '54-6.txt', surah: 'سورة الحديد'),
  const ThumonEntry(file: '54-7.txt', surah: 'سورة الحديد'),
  const ThumonEntry(file: '54-8.txt', surah: 'سورة الحديد'),
  const ThumonEntry(file: '55-1.txt', surah: 'سورة المجادلة'),
  const ThumonEntry(file: '55-2.txt', surah: 'سورة المجادلة'),
  const ThumonEntry(file: '55-3.txt', surah: 'سورة المجادلة و الحشر'),
  const ThumonEntry(file: '55-4.txt', surah: 'سورة الحشر'),
  const ThumonEntry(file: '55-5.txt', surah: 'سورة الحشر'),
  const ThumonEntry(file: '55-6.txt', surah: 'سورة الممتحنة'),
  const ThumonEntry(file: '55-7.txt', surah: 'سورة الممتحنة'),
  const ThumonEntry(file: '55-8.txt', surah: 'سورة الصف'),
  const ThumonEntry(file: '56-1.txt', surah: 'سورة الحمعة'),
  const ThumonEntry(file: '56-2.txt', surah: 'سورة المنافقون'),
  const ThumonEntry(file: '56-3.txt', surah: 'سورة المنافقون و التغابن'),
  const ThumonEntry(file: '56-4.txt', surah: 'سورة التغابن'),
  const ThumonEntry(file: '56-5.txt', surah: 'سورة الطلاق'),
  const ThumonEntry(file: '56-6.txt', surah: 'سورة الطلاق'),
  const ThumonEntry(file: '56-7.txt', surah: 'سورة التحريم'),
  const ThumonEntry(file: '56-8.txt', surah: 'سورة التحريم'),
  const ThumonEntry(file: '57-1.txt', surah: 'سورة الملك'),
  const ThumonEntry(file: '57-2.txt', surah: 'سورة الملك و القلم'),
  const ThumonEntry(file: '57-3.txt', surah: 'سورة القلم'),
  const ThumonEntry(file: '57-4.txt', surah: 'سورة القلم و الحاقة'),
  const ThumonEntry(file: '57-5.txt', surah: 'سورة الحاقة'),
  const ThumonEntry(file: '57-6.txt', surah: 'سورة المعارج'),
  const ThumonEntry(file: '57-7.txt', surah: 'سورة المعارج و نوح'),
  const ThumonEntry(file: '57-8.txt', surah: 'سورة نوح'),
  const ThumonEntry(file: '58-1.txt', surah: 'سورة الجن'),
  const ThumonEntry(file: '58-2.txt', surah: 'سورة نوح و المزمل'),
  const ThumonEntry(file: '58-3.txt', surah: 'سورة المزمل و المدثر'),
  const ThumonEntry(file: '58-4.txt', surah: 'سورة المدثر'),
  const ThumonEntry(file: '58-5.txt', surah: 'سورة القيامة'),
  const ThumonEntry(file: '58-6.txt', surah: 'سورة الإنسان'),
  const ThumonEntry(file: '58-7.txt', surah: 'سورة الإنسان و المرسلات'),
  const ThumonEntry(file: '58-8.txt', surah: 'سورة المرسلات'),
  const ThumonEntry(file: '59-1.txt', surah: 'سورة النبأ'),
  const ThumonEntry(file: '59-2.txt', surah: 'سورة النازعات'),
  const ThumonEntry(file: '59-3.txt', surah: 'سورة النازعات و عبس'),
  const ThumonEntry(file: '59-4.txt', surah: 'سورة التكوير'),
  const ThumonEntry(file: '59-5.txt', surah: 'سورة الإنفطار و المطففين'),
  const ThumonEntry(file: '59-6.txt', surah: 'سورة المطففين و الإنشقاق'),
  const ThumonEntry(file: '59-7.txt', surah: 'سورة الإنشقاق و البروج'),
  const ThumonEntry(file: '59-8.txt', surah: 'سورة البروج و الطارق'),
  const ThumonEntry(file: '60-1.txt', surah: 'حزب سبح'),
  const ThumonEntry(file: '60-2.txt', surah: 'حزب سبح'),
  const ThumonEntry(file: '60-3.txt', surah: 'حزب سبح'),
  const ThumonEntry(file: '60-4.txt', surah: 'حزب سبح'),
  const ThumonEntry(file: '60-5.txt', surah: 'حزب سبح'),
  const ThumonEntry(file: '60-6.txt', surah: 'حزب سبح'),
  const ThumonEntry(file: '60-7.txt', surah: 'حزب سبح'),
  const ThumonEntry(file: '60-8.txt', surah: 'حزب سبح'),
];
